#!/bin/bash

print_file_hex () {
    printf "0X%08x %s\n" $(stat -c "%s" "$1") "$1"
}

print_hex () {
    if [ -d "$1" ]; then
        printf "d--------- %s\n" "$1"
        for f in "$1"/*; do
            print_hex "$f"
        done
    elif [ -f "$1" ]; then
        print_file_hex "$1"
    fi
}

for file in "$@"; do
    print_hex "$file"
done
