#!/bin/bash
extra_args=
case $1 in
     Debug|Release|RelWithDebInfo|MinSizeRel|SanitizeAddress|SanitizeMemory|SanitizeThread|SanitizeUndefined|Valgrind|RelFlto)
         extra_args="-f build-$1.ninja"
         shift
         ;;
esac
if [ -e .git ]; then
   /usr/bin/ninja "$@"
elif [ -f build.ninja ]; then
    /usr/bin/ninja $extra_args "$@"
else
    dir=${PWD}
    cd $(~/bin/searchdir .)
    reldir=${dir#$PWD/}
    /usr/bin/ninja $extra_args $reldir/all "$@"
fi
