#!/bin/sh

while [ $(pwd) != "/" ]; do
    if [ -e .git ]; then
        if [ -x prebuild.pl ]; then
            echo "./prebuild.pl" "$@" > prebuild.out
            ./prebuild.pl "$@" >> prebuild.out
            exit 0;
        fi
    fi
    cd ..
done
echo "No project found"
exit 1;
